apiVersion: v1
kind: Pod
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs
    component: datanode
spec:
  containers:
  - name: datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    env:
    - name: SERVICE_PRECONDITION
      value: "namenode:9870"
    - name: CORE_CONF_fs_defaultFS
      value: "hdfs://namenode:9000"
    - name: CORE_CONF_hadoop_http_staticuser_users
      value: "root"
    - name: CORE_CONF_hadoop_proxyuser_hue_hosts
      value: "*"
    - name: CORE_CONF_hadoop_proxyuser_hue_groups
      value: "*"
    - name: CORE_CONF_io_compression_codecs
      value: "org.apache.hadoop.io.compress.SnappyCodec"
    - name: HDFS_CONF_dfs_webhdfs_enabled
      value: "true"
    - name: HDFS_CONF_dfs_permissions_enabled
      value: "false"
    - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
      value: "false"
