apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: hdfs
    component: namenode
  ports:
    - protocol: TCP
      port: 9870
      targetPort: 9870
      name: ui
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: rpc
