apiVersion: v1
kind: Pod
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
    component: namenode
spec:
  containers:
  - name: namenode
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    ports:
    - containerPort: 9000
      name: rpc
    - containerPort: 9870
      name: ui
    env:
    - name: CLUSTER_NAME
      value: "test"
    - name: CORE_CONF_fs_defaultFS
      value: "hdfs://namenode:9000"
    - name: CORE_CONF_hadoop_http_staticuser_users
      value: "root"
    - name: CORE_CONF_hadoop_proxyuser_hue_hosts
      value: "*"
    - name: CORE_CONF_hadoop_proxyuser_hue_groups
      value: "*"
    - name: CORE_CONF_io_compression_codecs
      value: "org.apache.hadoop.io.compress.SnappyCodec"
    - name: HDFS_CONF_dfs_webhdfs_enabled
      value: "true"
    - name: HDFS_CONF_dfs_permissions_enabled
      value: "false"
    - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
      value: "false"
